name: Create Release
on: [ push ]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{  github.run_number }}
          release_name: Release ${{ github.run_number }}
#            body: |
#              Changes in this Release
#              - First Change
#              - Second Change
          draft: false
          prerelease: false
