name: Create Release
on: [ push ]
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Read package.json
        id: package-json-current-version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.package-json-current-version.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: V${{ steps.package-json-current-version.outputs.version }}
          release_name: Release ${{ steps.package-json-current-version.outputs.version }}
#            body: |
#              Changes in this Release
#              - First Change
#              - Second Change
          draft: true
          prerelease: false
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          force-branch: true
      - name: Publish draft release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
      - name: run npm publish
        uses: actions/checkout@v3
      - name: publish
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish  --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
